Pigeon acceleration
GreenBlitz/Off-Season-2024 pull request #486
Opened 2024-12-01 15:28 UTC by YoniKiriaty

I'm back after 201 PRs

2024-12-01 16:09 UTC, Sh-Pe reviewed
For gyro we have an external object, aside to the wrapper. We'll probably want to simulate the gyro in the future too, so it's a good idea to create IAccelometer or something similar.

2024-12-12 23:17 UTC, tnrz135 submitted a review, later dismissed

2024-12-17 07:04 UTC, NoamRosenberg08 requested changes

2024-12-17 07:04 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/interfaces/IAccelerometer.java
> +
what about rotational acceleration?
Im not sure it's a feature but if it is we want is

2024-12-17 07:04 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/interfaces/IAccelerometer.java
> +
what about rotational acceleration?
Im not sure it's a feature but if it is we want is

2024-12-17 07:04 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/phoenix6/gyro/Pigeon2Gyro.java
> +
Why does pigeon2gyro not implementing IAccelerometer

2025-01-05 17:01 UTC, Sh-Pe commented on src/main/java/frc/robot/hardware/interfaces/IAccelerometer.java
> +
not a thing in their interface. I can calculate it if needed.

2025-01-09 19:08 UTC, yonnbro approved these changes, later dismissed

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/gyro/Pigeon2Gyro.java
> +	public Pigeon2Wrapper getGyro() {
why? you already have getDevice()

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	private final Supplier<ChassisSpeeds> robotSimulatedVelocityRelativeToRobot;
robot velocity relative to robot will always be zero

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	private double accelerationX;
space between

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +public class SimulatedAccelerometer extends GBSubsystem implements IAccelerometer {
I don't think this is a subsystem, you won't run commands on it

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	private ChassisSpeeds previousVelocity;
why don't you initialize this?

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +			/ TimeUtils.getCurrentTimeSeconds();
why do you divide by the current time and not the time difference?

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	}
I think you should get the velocity one time per loop instead of three

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/PigeonAccelerometer.java
> +public class PigeonAccelerometer extends Phoenix6Device implements IAccelerometer {
why is this separated from Pigeon2Gyro?

2025-01-10 19:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/Pigeon2Wrapper.java
> +	}
you can make this default in the interface

2025-01-10 20:01 UTC, Sh-Pe commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	}
wdym

2025-01-10 20:03 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	}
Do the get one time in beginning of periodic

2025-01-10 20:12 UTC, Sh-Pe commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/PigeonAccelerometer.java
> +public class PigeonAccelerometer extends Phoenix6Device implements IAccelerometer {
those are 2 different components, that happens to be controlled on the same device. 
idk. 
@YHerm what's your opinion?

2025-01-10 20:21 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +		double dt = lastUpdateTimestamp - currentTime;
TimeUtils.getLatestCycleTimeSeconds()

2025-01-10 20:21 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +		Logger.recordOutput(logPath + "AccelerationX", accelerationX);
Is this not simulated? Make name more informative

2025-01-11 13:40 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	private double lastUpdateTimestamp;
Why do you need this variable

2025-01-11 13:40 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +		double dt = TimeUtils.getLatestCycleTimeSeconds();
dt? Is it dangerous technology or driving test?

2025-01-16 10:53 UTC, Sh-Pe commented on src/main/java/frc/robot/hardware/phoenix6/accelerometer/SimulatedAccelerometer.java
> +	private double lastUpdateTimestamp;
alerts, if the user forgets to update it in the periodic (which has happened to me in the past in a different class)

2025-01-17 18:09 UTC, Sh-Pe commented
partial testing seems to indicate that adding an offset will be required

2025-01-26 18:39 UTC, RJ0907 commented on src/main/java/frc/robot/hardware/mechanisms/SimulatedAccelerometer.java
> +	private final Supplier<Double> noise;
Consider changing noise to fakeNoise to make it more clear
```suggestion
	private final Supplier<Double> fakeNoise;
```

2025-01-26 18:39 UTC, RJ0907 commented on src/main/java/frc/robot/hardware/mechanisms/SimulatedAccelerometer.java
> +		this.noise = () -> randomNumbersGenerator.nextGaussian() * noiseAmount;
You do not need a refrence of the Random objcet
```suggestion
		this.logPath = logPath;
		this.robotSimulatedVelocityRelativeToRobot = robotSimulatedVelocity;
		this.noise = () -> new Random.nextGaussian() * noiseAmount;
```

2025-01-26 18:39 UTC, RJ0907 commented on src/main/java/frc/robot/hardware/phoenix6/pigeon/PigeonHandler.java
> +	public PigeonHandler(String logPath, Pigeon2Wrapper pigeon, PigeonOffsets offsets) {
Consoder changing the name to pigeonWrapper
```suggestion
	public PigeonHandler(String logPath, Pigeon2Wrapper pigeonWrapper, PigeonOffsets offsets) {
```

2025-01-26 21:46 UTC, YHerm reviewed
i will go over it another time (its late) but look in maple library, how they did the gyro.

2025-01-29 12:28 UTC, Sh-Pe commented on src/main/java/frc/robot/hardware/mechanisms/SimulatedAccelerometer.java
> +		this.noise = () -> randomNumbersGenerator.nextGaussian() * noiseAmount;
i don't want to recalc the seed each time. performance

2025-01-29 18:51 UTC, Sh-Pe commented
suggestion (especially to YHerm): run `git diff filters-with-accel-with-swerve accel-test-filtered` to see how the new design of the pigeon impact the factories. 

latest commit hasn't been tested, yet the commit before it did. Still needs simulation testing.

2025-08-25 10:18 UTC, closed without merging