poseestimator simulated sources ⯮ (in the future) core
GreenBlitz/Off-Season-2024 pull request #503
Opened 2024-12-10 13:59 UTC by Sh-Pe

```                 .88888888:.
                88888888.88888.
              .8888888888888888.
              888888888888888888
              88' _`88'_  `88888
              88 88 88 88  88888
              88_88_::_88_:88888
              88:::,::,:::::8888
              88`:::::::::'`8888
             .88  `::::'    8:88.
            8888            `8:888.
          .8888'             `888888.
         .8888:..  .::.  ...:'8888888:.
        .8888.'     :'     `'::`88:88888
       .8888        '         `.888:8888.
      888:8         .           888:88888
    .888:88        .:           888:88888:
    8888888.       ::           88:888888
    `.::.888.      ::          .88888888
   .::::::.888.    ::         :::`8888'.:.
  ::::::::::.888   '         .::::::::::::
  ::::::::::::.8    '      .:8::::::::::::.
 .::::::::::::::.        .:888:::::::::::::
 :::::::::::::::88:.__..:88888:::::::::::'
  `'.:::::::::::88888888888.88:::::::::'
        `':::_:' -- '' -'-' `':_::::'````

2024-12-10 16:43 UTC, Sh-Pe commented
sim doesn't need robot testing

2024-12-12 05:32 UTC, NoamRosenberg08 requested changes

2024-12-12 05:32 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedSource.java
> +					Logger.recordOutput(logPath + "state", "not facing");
Maybe rename the not facing to "not detecting any tags"

2024-12-29 17:07 UTC, Yotam7 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedSource.java
> +public class SimulatedSource extends GBSubsystem implements VisionSource<AprilTagVisionData> {
Bad name, there can be many different types of sources, not just april tag

2025-01-16 15:44 UTC, DANNA2828 requested changes
::.:.
                        .:::::::....                   .     .:.=: 
     .*=            .=+++===+=-:::.....                .-.  .-:==. 
    *%%%-         .+++=======++-::::::....              ::.:==--.  
   -#%%%+.       =*###*+=--===+*#*+------:.        .##%+-..-=--    
     .+@@#=     +%%%#%%%%@@%%####%%%@%%%##++.      *#*##+--:-.     
         -#%=..*%%%%%%%%%%@@%%###%%%#%####+=-.   .*%#*=..=+-.      
           =%#*%%%%@%%@%%%%@%####%%%%##**==**-.:*#+      :=.       
            +**######%%%%%%#+=-:::=%%#%@@+-=--::+.        --.      
            +++++++********###*++=-:.:+*#*=-::...         .=:.     
           -++++++++*#%###%%#####*+=-::-=:::::...          -=:     
          .+*******#%@@@@@@@%%%%%%#**##=##*+-:....         .-=:    
          -***##%%@%#***#%%%@@@@@@%%*=-=#%%%#*-:...     .:---==.   
          *###%%%####********#*****-:::..:+#%%#*=:.::--=++-..      
         -**######%######***=--==++=:::::::-++***-.===-.           
       -+*****####@@@@@@@%%@@%###%%%@@@@@@@@%+:+-:..               
     :++++******###%@@@%@*+#+*##*+-*+:+=@@@*::.:::..               
   .+**- .********###%@@@@@@@@@@%#+@@@@@@#=:...:::..               
   -:.    .******########*+#*+-=*+=#+-=--::....:...                
  .-:.     .#****############*=+====----:::...::...                
  --.       .*#***####################*+=-::..:...                 
  =:.        .*########################*+-:::::..                  
 .=.          .+#####################*+=-::::::..                  
 --.          .+**########**********+=::::::::.                    
.*+:.         :*++: .+##############**+---:.                       
.#*+:         =*+=      .=#%%##########*:                          
:#+#+.       .+++.                  :*+-.                          
-*-.*:       .=-.                    =-:.                          
.#=.=-       :=-.                     -:.                          
 -#:         :*+.                    .++:                          
  .#+        :*+.                   :++.                           
    .        -*+.                  -==.                            
             -#+.                 -=+.                             
             =*+.                -==.                              
    .::-:::-:-::.              .=--:                               
   -#***+**+*++**.            =+++++=-:.....                       
          .-..                =*#####***+=+--=.                    
                                     :=*###*##:

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +				Logger.recordOutput(logPath + "state", "d=" + distanceMeters + "m");
maybe something to indicate that its out of range?

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +					Logger.recordOutput(logPath + "state", "returning");
consider returningPose, returningNoisedPose

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +	public boolean isRobotPointingIntoAngle(Rotation2d angle) {
```suggestion
	public boolean isRobotPointingToAngle(Rotation2d angle) {
```

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +		double angularNoise = simulatedPose.getRotation().getRadians() + angleNoise.get();
```suggestion
		double angularNoisedPose = simulatedPose.getRotation().getRadians() + angleNoise.get();
```

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +			new Pose2d(simulatedPose.getX() + xNoise, simulatedPose.getY() + yNoise, Rotation2d.fromRadians(angularNoise)),
you do 2 of the noise additions inside the return but not the third >:(

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +			new Double[] {xNoise, yNoise, angularNoise}
if this is to return only the noise then angularNoise is incorrect, see line 136 comment

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +			return data;
i think seperate these cases and add an alert if data is empty

2025-01-16 15:44 UTC, DANNA2828 commented on src/main/java/frc/robot/vision/sources/simulationsource/calibration.md
> + - Detection range etc. for each camera, in order to be able to simulate them.
.

2025-01-16 16:08 UTC, Sh-Pe commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +		double angularNoise = simulatedPose.getRotation().getRadians() + angleNoise.get();
It's just the angle, not the pose. Yet a hould be called angleNoise.

2025-01-16 16:22 UTC, Sh-Pe commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +				Logger.recordOutput(logPath + "state", "d=" + distanceMeters + "m");
It requires to extended the sidebar too much until it's unusable

2025-01-16 16:26 UTC, Sh-Pe commented on src/main/java/frc/robot/vision/sources/simulationsource/SimulatedAprilTagsSource.java
> +			return data;
Why would I? Sometimes the robot doesn't see anything

2025-08-24 12:07 UTC, closed without merging